pkg: &pkg d3-rs-circlepack
s3: &s3_bucket redsift-static
image: &default_image circleci/node:10-browsers

version: 2
jobs:
  build:
    docker:
      - image: *default_image
        environment:
          CIRCLE_TEST_REPORTS: ./build
    working_directory: ~/build  
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            npm install
            npm test
      - store_artifacts:
          path: ~/build/dist    
      - store_test_results:
          path: ~/build/junit      
  publish:
    docker:
      - image: *default_image
    steps:
      - checkout      
      - run:
          name: Publish package
          command: |
            pip install awscli
            aws s3 cp ${CIRCLE_ARTIFACTS}/distribution s3://$S3_BUCKET/reusable/$NAME/latest --recursive --acl public-read --cache-control max-age=7200,public
            VERSION=$(cat package.json | python -c 'import sys, json; print json.load(sys.stdin)["version"]')-$(git describe --exact-match --tags 2>/dev/null || git rev-parse --short HEAD)
            aws s3 cp ${CIRCLE_ARTIFACTS}/distribution s3://$S3_BUCKET/reusable/$NAME/$VERSION --recursive --acl public-read --cache-control max-age=31556926,public
            npm publish --access=public
workflows:
  version: 2
  build_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/      
      - publish:
          context: org-global
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/                