pkg: &pkg d3-rs-circlepack
s3: &s3_bucket redsift-static
image: &default_image circleci/node:10-node-browsers

version: 2
jobs:
  build:
    docker:
      - image: *default_image
        environment:
          CIRCLE_TEST_REPORTS: ./
    working_directory: ~/build  
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            npm install
            npm test
      - store_artifacts:
          path: ~/build/dist    
      - store_test_results:
          path: ~/build/junit      
  publish:
    docker:
      - image: *default_image
        environment:
          S3_BUCKET: *s3_bucket
          NAME: *pkg
    working_directory: ~/build        
    steps:
      - checkout      
      - run:
          name: Publish package
          command: |
            apt install python-pip
            pip install awscli
            echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
            npm publish --access=public            
            aws s3 cp ./dist s3://$S3_BUCKET/reusable/$NAME/latest --recursive --acl public-read --cache-control max-age=7200,public
            VERSION=$(cat package.json | python -c 'import sys, json; print json.load(sys.stdin)["version"]')-$(git describe --exact-match --tags 2>/dev/null || git rev-parse --short HEAD)
            aws s3 cp ./dist s3://$S3_BUCKET/reusable/$NAME/$VERSION --recursive --acl public-read --cache-control max-age=31556926,public
      - store_artifacts:
          path: ~/build/dist   

workflows:
  version: 2
  build_publish:
    jobs:
      - build    
      - publish:
          context: org-global
         